### ISSUE TITLE
Suggest Edits button not showing

### ISSUE THREAD

**Issue by HowieG** [mintlify/docs#185]
Sweet feature! Wonder if I'm doing anything wrong

<img width="766" alt="Screenshot 2024-05-24 at 4 31 42 PM" src="https://github.com/mintlify/docs/assets/15098079/1c666438-4d3b-4319-985d-f4c56cecfa84">
<img width="270" alt="Screenshot 2024-05-24 at 4 31 36 PM" src="https://github.com/mintlify/docs/assets/15098079/45797f5f-dac5-4a7a-aecc-77bd5bc2cb05">

**Comment by karanataryn** [comment]
Have the same issue, has anything been done to take a look at this?

**Comment by karanataryn** [comment]
Yes, here's mine: https://github.com/aryn-ai/docs

**Comment by HowieG** [comment]
Hey @fmerian! Our mint.json lives here:
https://github.com/AgentOps-AI/agentops/tree/main/docs

We've since removed the feedback option, but here's the code at the point in time when we did have it:
https://github.com/AgentOps-AI/agentops/blob/08e136cb23f3809a094532f28b8d6a06b9c39766/docs/mint.json

**Comment by fmerian** [comment]
@HowieG @karanataryn Hello there!

Quick update: The `feedback` props should be fixed now. You may need to redeploy your docs to see it live. Please let us know if it works! Thanks!

**Comment by karanataryn** [comment]
Thanks! I still don't see it on my end? Tried redeploying my docs.
