### ISSUE TITLE
OpenAPI Spec: Issues with uploading files

### ISSUE THREAD

**Issue by karanataryn** [mintlify/docs#345]
The Mintlify Web UI does not correctly upload files in the API request, passing it as a string instead of a file object. This leads to errors as seen below:
`{"detail":[{"type":"value_error","loc":["body","file"],"msg":"Value error, Expected UploadFile, received: <class 'str'>","input":"[object Object]","ctx":{"error":{}}}]}`

The construction of the cURL object is incorrect, as seen below: 
`curl --request POST \
  --url https://api.aryn.cloud/v1/document/partition \
  --header 'Authorization: Bearer REDACTED' \
  --header 'Content-Type: multipart/form-data' \
  --form 'file={}'`

which should instead contain `--form 'file=@example.pdf'`

**Comment by mayank-ekacare** [comment]
@karanataryn is this fixed, I am still facing same error

**Comment by karanataryn** [comment]
> @karanataryn is this fixed, I am still facing same error

I don't think so.

**Comment by Gawc1uuu** [comment]
@fmerian are there any updates on this? i run into the same issue :)

**Comment by spencerjsmall** [comment]
Bump on this.

**Comment by krakenftw** [comment]
Bump

**Comment by NayamAmarshe** [comment]
We're having the same issue. Bump.

**Comment by mdhvcgf** [comment]
same here

**Comment by iyuvraajsingh** [comment]
Hello, Any update. This issue is really bugging us.

**Comment by mayank-ekacare** [comment]
Team mintlify,

What is stopping us to look into issue?

@tiffany-mintlify @katemintlify @mintlifydavid

**Comment by dino475** [comment]
Hi everyone! We so appreciate your patience as we continue to iron out the kinks in our product. We just addressed this issue and would love your feedback on the resolution!

**Comment by pierre-tabet** [comment]
Thanks for the fix @dino475 ! Single file uploads work great now, but arrays of files (using the files[] parameter) still don't work correctly. Could you address this case too? Thank you

**Comment by dino475** [comment]
Hey everyone, we're working on this and will follow up here shortly

**Comment by pierre-tabet** [comment]
Hi @dino475 , just following up on arrays of files (using the files[] parameter) still don't work correctly. Could you address this case too? Thank you

**Comment by lai-bianca** [comment]
@dino475 Any updates on the PR mentioned on June 1? I suspect the issues mentioned in this thread are causing the "011000010111000001101001" strings to be added to our sample scripts.

**Comment by tiffany-mintlify** [comment]
hey @Segfaultd we merged a fix 2 weeks ago but are you still running into issues?

**Comment by Segfaultd** [comment]
> hey [@Segfaultd](https://github.com/Segfaultd) we merged a fix 2 weeks ago but are you still running into issues?

Hi, yes well the exact same issue as referenced in first place. When you upload a file, the generated payload is empty ```file={}```

**Comment by dino475** [comment]
> > hey [@Segfaultd](https://github.com/Segfaultd) we merged a fix 2 weeks ago but are you still running into issues?
> 
> Hi, yes well the exact same issue as referenced in first place. When you upload a file, the generated payload is empty `file={}`

Hi @Segfaultd can you please share a link to where this is happening so we can reproduce and record the issue for our team?
